import { v4 as uuidv4 } from 'uuid';

export const timesData = [
  {
    id: uuidv4(),
    nome: 'Back-End',
    cor: '#57C278',
  },
  {
    id: uuidv4(),
    nome: 'Front-End',
    cor: '#82CFFA',
  },
  {
    id: uuidv4(),
    nome: 'Data Science',
    cor: '#A6D157',
  },
  {
    id: uuidv4(),
    nome: 'Devops',
    cor: '#E06B69',
  },
  {
    id: uuidv4(),
    nome: 'UX e Design',
    cor: '#DB6EBF',
  },
  {
    id: uuidv4(),
    nome: 'Mobile',
    cor: '#FFBA05',
  },
  {
    id: uuidv4(),
    nome: 'Inovação e Gestão',
    cor: '#FF8A29',
  },
];

export const colaboradoresInicial = [
  {
    id: uuidv4(),
    nome: 'LUIZ FERNANDO RIBEIRO',
    cargo: 'Desenvolvedor de software e instrutor',
    imagem: 'https://github.com/lfrprazeres.png',
    time: timesData[4].nome,
    favorito: false,
  },
  {
    id: uuidv4(),
    nome: 'JULIANA AMOASEI',
    cargo: 'Desenvolvedora de software e instrutora',
    imagem: 'https://www.alura.com.br/assets/img/lideres/juliana-amoasei.1647533644.jpeg',
    time: timesData[0].nome,
    favorito: false,
  },
  {
    id: uuidv4(),
    nome: 'DANIEL ARTINE',
    cargo: 'Engenheiro de Software na Stone Age',
    imagem: 'https://www.alura.com.br/assets/img/lideres/daniel-artine.1647533644.jpeg',
    time: timesData[0].nome,
    favorito: false,
  },
  {
    id: uuidv4(),
    nome: 'GUILHERME LIMA',
    cargo: 'Desenvolvedor Python e Javascript na Alura',
    imagem: '	https://www.alura.com.br/assets/img/lideres/guilherme-lima.1647533644.jpeg',
    time: timesData[1].nome,
    favorito: false,
  },
  {
    id: uuidv4(),
    nome: 'PAULO SILVEIRA',
    cargo: 'Hipster e CEO da Alura',
    imagem: 'https://www.alura.com.br/assets/img/lideres/paulo-silveira.1647533644.jpeg',
    time: timesData[6].nome,
    favorito: false,
  },

  {
    id: uuidv4(),
    nome: 'CAROL SANTOS',
    cargo: 'Tech lead',
    imagem: 'https://github.com/carolsvntos.png',
    time: timesData[1].nome,
    favorito: false,
  },
  {
    id: uuidv4(),
    nome: 'GENESIS LIMA',
    cargo: 'Desenvolvedora Web',
    imagem: 'https://github.com/g-101.png',
    time: timesData[1].nome,
    favorito: false,
  },
  {
    id: uuidv4(),
    nome: 'LUIZ FERNANDO RIBEIRO',
    cargo: 'Desenvolvedor de software e instrutor',
    imagem: 'https://github.com/lfrprazeres.png',
    time: timesData[5].nome,
    favorito: false,
  },
  {
    id: uuidv4(),
    nome: 'JULIANA AMOASEI',
    cargo: 'Desenvolvedora de software e instrutora',
    imagem: 'https://www.alura.com.br/assets/img/lideres/juliana-amoasei.1647533644.jpeg',
    time: timesData[3].nome,
    favorito: false,
  },
  {
    id: uuidv4(),
    nome: 'DANIEL ARTINE',
    cargo: 'Engenheiro de Software na Stone Age',
    imagem: 'https://www.alura.com.br/assets/img/lideres/daniel-artine.1647533644.jpeg',
    time: timesData[3].nome,
    favorito: false,
  },
  {
    id: uuidv4(),
    nome: 'GUILHERME LIMA',
    cargo: 'Desenvolvedor Python e Javascript na Alura',
    imagem: '	https://www.alura.com.br/assets/img/lideres/guilherme-lima.1647533644.jpeg',
    time: timesData[2].nome,
    favorito: false,
  },
  {
    id: uuidv4(),
    nome: 'PAULO SILVEIRA',
    cargo: 'Hipster e CEO da Alura',
    imagem: 'https://www.alura.com.br/assets/img/lideres/paulo-silveira.1647533644.jpeg',
    time: timesData[0].nome,
    favorito: false,
  },

  {
    id: uuidv4(),
    nome: 'CAROL SANTOS',
    cargo: 'Tech lead',
    imagem: 'https://github.com/carolsvntos.png',
    time: timesData[4].nome,
    favorito: false,
  },
  {
    id: uuidv4(),
    nome: 'GENESIS LIMA',
    cargo: 'Desenvolvedora Web',
    imagem: 'https://github.com/g-101.png',
    time: timesData[0].nome,
    favorito: false,
  },
];
